openapi: 3.0.2
info:
  title: Anti-fraud API (deprecated)
  version: '1.0'
  description: ''
tags:
  - name: Anti-fraud endpoint
    description: Интерфейсы Anti-fraud сервиса для BI.ZONE BCFP.
servers: []
paths:
  /incident-results:
    summary: Интерфейс для передачи резолюции от BI.ZONE BCFP
    description: Передача отложенной резолюции от BI.ZONE в Интернет банк после рассмотрения.
    post:
      operationId: postResolution
      summary: Передать решение BCFP после рассмотрения.
      tags:
        - Anti-fraud endpoint
      requestBody:
        description: Данные из решения BCFP.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateResponse'
      description: ''
    parameters: []
components:
  schemas:
    UpdateRequest:
      title: Resolution by BCFP
      type: object
      required:
        - version
        - eventId
        - clientTransactionId
        - eventDescription
        - UpdateStatus
      properties:
        version:
          type: string
          description: Используемая версия JSON протокола
          enum:
            - '2.1'
        eventId:
          type: string
          description: Идентификатор события
        eventDescription:
          type: string
          description: Описание события
        clientTransactionId:
          type: string
          description: Идентификатор клиентской транзакции
        UpdateStatus:
          $ref: '#/components/schemas/UpdateStatus'
    UpdateStatus:
      title: Status
      type: object
      required:
        - actionCode
      properties:
        action:
          type: string
          enum:
            - ALLOW
            - DENY
    UpdateResponse:
      title: Response to BCFP
      type: object
      required:
        - version
        - eventId
        - clientTransactionId
        - eventDescription
        - return
      properties:
        version:
          type: string
          description: Используемая версия JSON протокола
          enum:
            - '2.1'
        eventId:
          type: string
          description: Идентификатор события
        eventDescription:
          type: string
          description: Описание события
        clientTransactionId:
          type: string
          description: Идентификатор клиентской транзакции
        return:
          type: string
          enum:
            - SUCCESS
            - FAIL
        description:
          type: string
          description: Обязательное поле если return = FAIL
