openapi: 3.0.0
info:
  title: Self-employed service
  version: '0.1'
  description: |
    Функциональность для самозанятых.
    Сервис интегрируется с прикладной подсистемой АИС «Налог-3», обеспечивающей налогообложение доходов физических лиц, полученных от профессиональной деятельности.

    Оснавные кейсы предоставляемые сервисом:
    1. Постановка и снятие с учёта.
    2. Регистраци дохода.
    3. Получение справок.
    4. Получение справочников.
    5. Работа с оповещениями.
  contact:
    name: Reinhold Shekhtel
    email: raikbitters@gmail.com
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas: {}
  securitySchemes: {}
