openapi: 3.0.0
info:
  title: Self-employed service
  version: '0.1'
  description: |
    Функциональность для самозанятых.
    Сервис интегрируется с прикладной подсистемой АИС «Налог-3», обеспечивающей налогообложение доходов физических лиц, полученных от профессиональной деятельности.

    Основные кейсы предоставляемые сервисом:

    1. Постановка и снятие с учёта.
    2. Регистрация дохода.
    3. Получение справок.
    4. Получение справочников.
    5. Работа с оповещениями.
  contact:
    name: Reinhold Shekhtel
    email: raikbitters@gmail.com
tags:
  - name: self-employers
    description: Self-employers collection
servers:
  - url: 'http://localhost:3000'
paths:
  '/restrictions/{vatin}':
    get:
      summary: Your GET endpoint
      tags:
        - self-employers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Restriction'
      operationId: get-restrictions
      description: |-
        Первичная проверка существующих ограничений для регистрации налогоплательщика. Обязательна перед регистрацией.
        Полный набор проверок делается только в момент постановки на учет в ПП ЦУН АИС «Налог-3». То есть, при успешном прохождении первичной проверки на наличие ограничений при постановке на учет, нет гарантии, что при фактической постановке на учет не последует отказа.
      parameters:
        - schema:
            type: string
            format: uuid
            example: 81434a30-e825-473a-a2a6-397ae774333e
          in: header
          name: requestId
          description: Уникальный номер запроса
          required: true
    parameters:
      - schema:
          type: string
        name: vatin
        in: path
        required: true
        description: ИНН
components:
  schemas:
    Restriction:
      title: Restriction
      type: object
      description: Резолюция о результатах первичной проверки.
      properties:
        result:
          type: string
          enum:
            - ALLOW
            - DENY
          description: |-
            Результат запроса: 
            ALLOW – можно ставить на учет, 
            DENY – нельзя ставить на учет.
        code:
          type: string
          description: Получаем если результат = DENY.
      x-examples:
        example-1:
          result: ALLOW
          code: string
  securitySchemes: {}
