openapi: 3.0.0
info:
  title: Self-employed service
  version: '0.1'
  description: |
    Функциональность для самозанятых.
    Сервис интегрируется с прикладной подсистемой АИС «Налог-3», обеспечивающей налогообложение доходов физических лиц, полученных от профессиональной деятельности.

    Основные кейсы предоставляемые сервисом:

    1. Постановка и снятие с учёта.
    2. Регистрация дохода.
    3. Получение справок.
    4. Получение справочников.
    5. Работа с оповещениями.
  contact:
    name: Reinhold Shekhtel
    email: raikbitters@gmail.com
servers:
  - url: 'http://localhost:3000'
paths:
  '/restrictions/{vatin}':
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    enum:
                      - ALLOW
                      - DENY
                  code:
                    type: string
      operationId: get-restrictions
      description: Проверка существующих ограничений для регистрации налогоплательщика.
      parameters:
        - schema:
            type: string
            format: uuid
          in: header
          name: requestId
          description: ''
    parameters:
      - schema:
          type: string
        name: vatin
        in: path
        required: true
        description: ИНН
components:
  schemas:
    Restriction:
      title: Restriction
      type: object
      description: ''
      properties:
        result:
          type: string
          enum:
            - ALLOW
            - DENY
          description: |-
            Результат запроса: 
            ALLOW – можно ставить на учет, 
            DENY – нельзя ставить на учет.
        code:
          type: string
          description: Получаем если результат = DENY.
  securitySchemes: {}
