openapi: 3.0.0
info:
  title: Self-employed service
  version: '0.1'
  description: |
    Функциональность для самозанятых.
    Сервис интегрируется с прикладной подсистемой АИС «Налог-3», обеспечивающей налогообложение доходов физических лиц, полученных от профессиональной деятельности.

    Основные кейсы предоставляемые сервисом:

    1. Постановка и снятие с учёта.
    2. Регистрация дохода.
    3. Получение справок.
    4. Получение справочников.
    5. Работа с оповещениями.
  contact:
    name: Reinhold Shekhtel
    email: raikbitters@gmail.com
tags:
  - name: self-employers
    description: Self-employers collection
servers:
  - url: 'http://localhost:3000'
paths:
  '/restrictions/{vatin}':
    get:
      summary: GET Restrictions
      tags:
        - self-employers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Restriction'
      operationId: get-restrictions
      description: |-
        Первичная проверка существующих ограничений для регистрации налогоплательщика. Обязательна перед регистрацией.
        Полный набор проверок делается только в момент постановки на учет в ПП ЦУН АИС «Налог-3». То есть, при успешном прохождении первичной проверки на наличие ограничений при постановке на учет, нет гарантии, что при фактической постановке на учет не последует отказа.
      parameters:
        - schema:
            type: string
            format: uuid
            example: 81434a30-e825-473a-a2a6-397ae774333e
          in: header
          name: requestId
          description: Уникальный номер запроса
          required: true
    parameters:
      - schema:
          type: string
        name: vatin
        in: path
        required: true
        description: ИНН
  '/self-employers/{vatin}':
    parameters:
      - schema:
          type: string
        name: vatin
        in: path
        required: true
        description: ИНН
    get:
      summary: GET self-employer info
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Self-employer'
      operationId: get-self-employers-vatin
      description: ''
    put:
      summary: Update self-employer info
      operationId: put-self-employers-vatin
      responses:
        '200':
          description: OK
    delete:
      summary: Unregistration self-employer
      operationId: delete-self-employers-vatin
      responses:
        '200':
          description: OK
      description: ''
  /self-employers:
    post:
      summary: ''
      operationId: post-self-employers
      responses:
        '200':
          description: OK
components:
  schemas:
    Restriction:
      title: Restriction
      type: object
      description: Резолюция о результатах первичной проверки.
      properties:
        result:
          type: string
          enum:
            - ALLOW
            - DENY
          description: |-
            Результат запроса: 
            ALLOW – можно ставить на учет, 
            DENY – нельзя ставить на учет.
        code:
          type: string
          description: Получаем если результат = DENY.
      x-examples:
        example-1:
          result: ALLOW
          code: string
    Self-employer:
      title: Self-employer
      type: object
      description: ''
      properties:
        vatin:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        birthday:
          type: string
          format: date
        passport_series:
          type: string
        passport_number:
          type: string
        activity_code:
          type: string
        timestamp_create:
          type: string
        region_code:
          type: string
      required:
        - vatin
        - first_name
        - last_name
        - birthday
        - passport_series
        - passport_number
        - activity_code
        - timestamp_create
        - region_code
  securitySchemes: {}
