openapi: 3.0.0
info:
  title: Self-employed service
  version: '0.1'
  description: |
    Функциональность для самозанятых.
    Сервис интегрируется с прикладной подсистемой АИС «Налог-3», обеспечивающей налогообложение доходов физических лиц, полученных от профессиональной деятельности.

    Основные кейсы предоставляемые сервисом:

    1. Постановка и снятие с учёта.
    2. Регистрация дохода.
    3. Получение справок.
    4. Получение справочников.
    5. Работа с оповещениями.
  contact:
    name: Reinhold Shekhtel
    email: raikbitters@gmail.com
tags:
  - name: self-employers
    description: Self-employers collection
servers:
  - url: 'http://localhost:3000'
paths:
  '/restrictions/{vatin}':
    get:
      summary: GET Restrictions
      tags:
        - self-employers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Restriction'
      operationId: get-restrictions
      description: |-
        Первичная проверка существующих ограничений для регистрации налогоплательщика. Обязательна перед регистрацией.
        Полный набор проверок делается только в момент постановки на учет в ПП ЦУН АИС «Налог-3». То есть, при успешном прохождении первичной проверки на наличие ограничений при постановке на учет, нет гарантии, что при фактической постановке на учет не последует отказа.
      parameters: []
    parameters:
      - schema:
          type: string
        name: vatin
        in: path
        required: true
        description: ИНН
  '/self-employers/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: ИНН
    get:
      summary: GET self-employer info
      tags: []
      responses:
        '200':
          description: OK
      operationId: get-self-employers-vatin
      description: ''
    put:
      summary: Update self-employer info
      operationId: put-self-employers-vatin
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SelfEmployer'
            examples: {}
      description: ''
    delete:
      summary: Unregistration self-employer
      operationId: delete-self-employers-vatin
      responses:
        '200':
          description: OK
      description: ''
      parameters:
        - schema:
            type: string
          in: query
          name: reasons
          required: true
          description: Код причины снятия с учёта
  /self-employers:
    post:
      summary: Create self-employer
      operationId: post-self-employers
      responses:
        '200':
          description: OK
      description: Регистрация самозанятого
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Registration'
        description: ''
    get:
      summary: ''
      operationId: get-self-employers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SelfEmployerInfo'
      parameters:
        - schema:
            type: string
          in: query
          name: user_id
          required: true
      description: ''
components:
  schemas:
    Restriction:
      title: Restriction
      type: object
      description: Резолюция по результатам первичной проверки.
      x-examples: {}
      properties:
        result:
          type: string
          enum:
            - ALLOW
            - DENY
          description: |-
            Результат запроса: 
            ALLOW – можно ставить на учет, 
            DENY – нельзя ставить на учет.
        deny_code:
          type: string
          description: Получаем если результат = DENY.
    Registration:
      title: Registration application
      description: Обязательные данные для постановки на учёт.
      x-examples: {}
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        birthday:
          type: string
          format: date
        passport_series:
          type: string
        passport_number:
          type: string
      required:
        - first_name
        - last_name
        - birthday
        - passport_series
        - passport_number
    SelfEmployer:
      title: Self-employer
      type: object
      description: Информацию о самозанятом.
      properties:
        id:
          type: integer
          description: ИНН
          format: int64
        status:
          type: string
          enum:
            - ACTIVE
            - UNACTIVE
            - PENDING
        user_id:
          type: integer
          format: int64
        activity_code:
          type: string
        region_code:
          type: string
    SelfEmployerInfo:
      title: Self-employer Info
      description: Информация о самозанятом
      allOf:
        - $ref: '#/components/schemas/SelfEmployer'
        - type: object
          properties:
            timestamp_create:
              type: string
              format: date-time
            timestamp_update:
              type: string
              format: date-time
            last_application_id:
              type: integer
              format: int64
      x-examples: {}
    Application:
      title: Application
      type: object
      description: |-
        Заявка для налоговой. Создаётся для операций с ФНС:
        * Регистрация пользователя.
        * Снятие с учёта пользователя.
        * Привязка пользователя к интернет банку.ую
      properties:
        id:
          type: integer
          format: int64
          description: ''
        order_id:
          type: string
          description: ID заявки в ФНС
        application_type:
          type: string
          description: Тип заявки
        result:
          type: string
          enum:
            - COMPLETED
            - FAILED
            - IN_PROGRESS
            - ORDER_REGISTERED
          description: Текущий результат заявки
        rejection_code:
          type: string
          description: Причина отказа
  securitySchemes: {}
