openapi: '3.0.2'
info:
  title: Deposit service
  version: '1.0'
  description: |
    ### Сервис для работы с депозитами клиентов интернет-банка
    Позволяет решать задачи управления депозитами физических и юридических лиц.

    Предоставляет функциональность:
    * открытие и закрытие депозита;
    * получение списка продуктовых предложений по депозитам;
    * получение списка открытых и закрытых депозитов;
    * получение операций по группе депозитов.

servers:
  - url: https://api.example.com
    description: SwaggerHub API Auto Mocking
  - url: '{protocol}://{server}:{port}'
    description: Local server
    variables:
      protocol:
        default: 'http'
      server:
        default: 'localhost'
      port:
        default: '7019'
paths:
  /customers/private/rates:
    get:
      summary: Получить доступные к открытию депозиты для пользователя.
      parameters:
        - $ref: '#/components/parameters/X-Request-ID'
      responses:
        '200':
          description: A list of deposit offers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DepositRate'
              examples:
                Private:
                  value:
                    id: 800936587281
                    typeCode: "1610"
                    parentTypeCode: "1610"
                    type: "Пенсионный online"
                    termsUrl: "https://www.bspb.ru/retail/deposits/pensionnyj-online/"
                    online: true
                    customPeriod: false
                    topupAllowed: true
                    reinvestInterest: true
                    cancellationAllowed: false
                    initialAmountWithdrawAllowed: false
                    interestWithdrawAllowed: false
                    prolongationAllowed: true
                    hidden: false
                    interestsPayments: "MONTHLY"
                    currency: "RUB"
                    minAmount: 1000.00
                    maxAmount: 100000000.00
                    minTopUpAmount: 0.01
                    minDays: 367
                    rate: 4.0
                    dynamicRatesDescription: ""
                    cancellationPenalties: {}
                    validSince: "2019-07-15T00:00:00.000"
                    prolongationTypeCode: "1611"
                    raised: false
                Сorporate:
                  value:
                    id : 672108579681
                    typeCode: "5201"
                    type: "Срочный депозит"
                    termsUrl: ""
                    online: false
                    customPeriod: true
                    topupAllowed: false
                    reinvestInterest: false
                    cancellationAllowed: false
                    initialAmountWithdrawAllowed: false
                    interestWithdrawAllowed: false
                    prolongationAllowed: false
                    hidden: false
                    interestsPayments: "MATURITY"
                    currency: "RUB"
                    minAmount: 10000.00
                    maxAmount: 100000000.00
                    minTopUpAmount: 0.00
                    minDays: 1096
                    rate: 6.90
                    dynamicRatesDescription: ""
                    cancellationPenalties: { "0": 0.01 }
                    validSince: "2018-09-03T00:00:00.000"
                    raised: false
        '5XX':
          $ref: '#/components/responses/Unexpected'
  /customers/private/{dboId}/deposits:
    get:
      summary: Получить текущие депозиты ФЛ
      parameters:
        - $ref: '#/components/parameters/X-Request-ID'
      responses:
        '200':
          description: OK             
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '5XX':
          $ref: '#/components/responses/Unexpected'
  /customers/private/{dboId}/place:
    post:
      summary: Открыть депозит ФЛ
      parameters:
        - $ref: '#/components/parameters/X-Request-ID'
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '5XX':
          $ref: '#/components/responses/Unexpected'
  /customers/private/{dboId}/close/{depositId}:
    post:
      summary: Закрыть депозит ФЛ
      parameters:
        - $ref: '#/components/parameters/X-Request-ID'
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '5XX':
          $ref: '#/components/responses/Unexpected'
  /customers/sole-proprietor/rates:
    get:
      summary: Получить доступные к открытию депозиты ИП
      parameters:
        - $ref: '#/components/parameters/X-Request-ID'
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '5XX':
          $ref: '#/components/responses/Unexpected'
  /customers/corporate/rates:
    get:
      summary: Получить доступные к открытию депозиты ЮЛ
      parameters:
        - $ref: '#/components/parameters/X-Request-ID'
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '5XX':
          $ref: '#/components/responses/Unexpected'
  /customers/corporate/{dboId}/deposits:
    get:
      summary: Получить текущие депозиты ЮЛ
      parameters:
        - $ref: '#/components/parameters/X-Request-ID'
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '5XX':
          $ref: '#/components/responses/Unexpected'
  /customers/corporate/{dboId}/transactions:
    get:
      summary: Получить операции по депозиту ЮЛ
      parameters:
        - $ref: '#/components/parameters/X-Request-ID'
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '5XX':
          $ref: '#/components/responses/Unexpected'
  /customers/corporate/{dboId}/place:
    post:
      summary: Открыть вклад ЮЛ
      parameters:
        - $ref: '#/components/parameters/X-Request-ID'
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '5XX':
          $ref: '#/components/responses/Unexpected'
  /customers/corporate/{dboId}/close/{depositId}:
    post:
      summary: Закрыть вклад ЮЛ
      parameters:
        - $ref: '#/components/parameters/X-Request-ID'
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '5XX':
          $ref: '#/components/responses/Unexpected'
components:
  schemas:
    DepositRate:
      title: Deposit Rate Object
      type: object
      properties:
        id:
          type: integer
          description: 'ID схемы начисления процентов для 
          определенного вида депозитного договора.'
          nullable: true
          example: 800936587281
        typeCode:
          type: string
          description: 'Код вида депозитного договора в ЦФТ.'
          nullable: true
          example: "1610"
        parentTypeCode:
          type: string
          description: 'Код вида вклада для доп. вложения.'
          nullable: true
          example: "1610"
        type:
          type: string
          description: 'Наименование вклада.'
          nullable: true
          example: "Пенсионный online"
        termsUrl:
          type: string
          description: 'Ссылка на страницу ИБ с 
          подробным описанием депозита.'
          nullable: true
          example: "https://www.bspb.ru/retail/deposits/pensionnyj-online/"
        online:
          type: boolean
          description: 'Признак возможности открытия вклада 
          online в ИБ.'
          example: true
        customPeriod:
          type: boolean
          description: 'Вернёт "true", если у вида вклада в АБС 
          есть ссылка на справочник «СПБ. Депозиты особые условия».'
          example: false
        topupAllowed:
          type: boolean
          description: 'Признак возможности 
          пополнения/дополнительных взносов.'
          example: true
        reinvestInterest:
          type: boolean
          description: 'Признак реинвестирования накопленных 
          процентов.'
          example: true
        cancellationAllowed:
          type: boolean
          description: 'Признак возможности досрочного закрытия 
          вклада.'
          example: false
        isTopupWithdrawAllowed:
          type: boolean
          description: 'Возвращаемое значение сервиса не 
          используется. Удалено.'
          deprecated: true
          example: false
        initialAmountWithdrawAllowed:
          type: boolean
          description: 'Признак возможности снятия средств с 
          депозитного договора.'
          example: false
        interestWithdrawAllowed:
          type: boolean
          description: 'Признак возможности снятия накопленных 
          процентов.'
          example: false
        prolongationAllowed:
          type: boolean
          description: 'Признак возможности пролонгации депозита.'
          example: true
        hidden:
          type: boolean
          description: 'Возвращается "true", если typeCode 
          1621, 1622 или 300.'
          example: false
        interestsPayments:
          type: string
          description: 'Период выплаты процентов. Значения:
          MONTHLY, QUARTERLY, MATURITY.'
          example: 'MONTHLY'
        currency:
          type: string
          description: 'Валюта вклада.'
          example: "RUB"
        minAmount:
          type: number
          description: 'Минимальная сумма вклада.'
          example: 1000.00
        maxAmount:
          type: number
          description: 'Максимальная сумма вклада.'
          example: 5000000.00
        minTopUpAmount:
          type: number
          description: 'Минимальная сумма пополнения депозита.'
          example: 0.01
        maxTopUpAmount:
          type: number
          description: 'Максимальная сумма пополнения депозита.'
          deprecated: true
          example: 5000000.00
        minDays:
          type: integer
          description: 'Минимальный срок вклада для случаев вручную 
          указываемого срока или свободного срока.'
          example: 367
        rate:
          type: number
          description: 'Ставка, % годовых.'
          example: 4.0
        rateExtra:
          type: number
          description: 'Значение уточняется.'
          deprecated: true
          example: 4.0
        dynamicRatesDescription:
          type: string
          description: 'dynamicRatesDescription.'
          example: "Ставка LIBOR overnight - 1.4%"
        cancellationPenalties:
          description: 'Штрафная процентная ставка при досрочном 
          закрытии вклада.'
        validSince:
          type: string
          format: date-time
          description: 'Дата, с которой можно открывать вклад.'
        prolongationTypeCode:
          type: string
          description: 'Код вида договора для автоматической 
          пролонгации.'
          example: "1611"
        raised:
          type: boolean
          description: 'Всегда возвращает false.'
          example: false
  parameters:
    X-Request-ID:
      in: header
      name: RequestId
      schema:
       type: string
       format: uuid
      required: true
  responses:
    BadRequest:
      description: Bad request. Object ID must be an integer and larger than 0.
    NotFound:
      description: A object with the specified ID was not found.
    Unexpected:
      description: Unexpected error.