@startuml 1c-directbank-components

!startsub COMPONENT
component "1C DirectBank API Gateway" as 1CDirect <<service>>
!endsub

!startsub PUBLIC_API
interface "POST /GetSettings" as getSettings
1CDirect --() getSettings

interface "POST /LogonCert" as logonCert
1CDirect --() logonCert

interface "POST /LogonOTP" as logonOTP
1CDirect --() logonOTP

interface "POST /Logon" as logon
1CDirect --() logon
!endsub

@enduml