@startuml (id=ca-service-component)

    component "Certificate Authority service" as CAService <<Component>>


@enduml

@startuml (id=ca-service-interfaces)

!include ca-service.puml

!startsub getCerts

    interface "GET /certs" as getCerts
    CAService --() getCerts

!endsub

@enduml