@startuml certificate-authority-components

!startsub COMPONENT

    component "Certificate Authority service" as CAService <<Component>>

!endsub

!startsub API

    interface "GET /certs" as getCerts
    CAService --() getCerts

!endsub

@enduml