@startuml (id=customer-service-component)

    component "Customer service" as CustomerService <<Component>>

@enduml


@startuml (id=customer-service-interfaces)

!startsub getCustomers

    interface "GET /customers" as getCustomers
    CustomerService --() getCustomers

!endsub

@enduml