@startuml high-level-model-components

component "АИС Налог-3\nПП НПД" as Tax3 <<component>>
component "Self-employed service" as SelfEmplService <<component>>
component "Auth service" as AuthService <<component>>
component "Kafka Message bus" as  Kafka <<component>>

SelfEmplService ..> Tax3: use APIs
SelfEmplService ..> AuthService: change User role
SelfEmplService .right.> Kafka: consume events

@enduml



@startuml self-employer-components

component "АИС Налог-3\nПП НПД" as Tax3 <<component>>
interface "GetTaxpayerRestrictionsRequest" as getTaxpayerRestrictions
interface "PostRegistrationRequest\nGetRegistrationStatusRequest" as postTaxpayerRegistration
interface "GetTaxpayerStatusRequest" as getTaxpayerStatus
interface "PutTaxpayerDataRequest" as putTaxpayerData
interface "GetGrantedPermissionsRequest" as getGrantedPermission
interface "GetInnByPersonalInfoRequestV3" as getInnByPersonalInfo
interface "PostBindPartnerWithInnRequest\nGetBindPartnerStatusRequest" as postPartnerBindInn
interface "PostBindPartnerWithPhoneRequest\nGetBindPartnerStatusRequest" as postPartnerBindPhone
interface "PostUnbindPartnerRequest" as postPartnerUnbind
interface "PostUnregistrationRequestV2\nGetUnregistrationStatusRequest" as postTaxpayerUnregistration

Tax3 --() getTaxpayerRestrictions
Tax3 --() postTaxpayerRegistration
Tax3 --() getTaxpayerStatus
Tax3 --() putTaxpayerData
Tax3 --() postPartnerBindInn
Tax3 --() postPartnerBindPhone
Tax3 --() postTaxpayerUnregistration
Tax3 --() postPartnerUnbind
Tax3 --() getGrantedPermission
Tax3 --() getInnByPersonalInfo

component "Self-employed service" as SelfEmplService <<service>> {

component "Registration info" as RegInfo <<component>>
interface "GET /restrictions/{vatin}" as getRestrictions
interface "POST /vatin-request/" as postVatinRequest

RegInfo -up-( getTaxpayerRestrictions
RegInfo -up-( getInnByPersonalInfo

RegInfo --() getRestrictions
RegInfo --() postVatinRequest

component "Create self-employer" as CreateSelfEmpl <<component>>
interface "POST /self-employers/" as postSelfEmpls

CreateSelfEmpl --() postSelfEmpls

CreateSelfEmpl -up-( postTaxpayerRegistration
CreateSelfEmpl -up-( postPartnerBindInn
CreateSelfEmpl -up-( postPartnerBindPhone

component "Local self-employers data" as Local <<component>>
interface "GET /self-employers/" as getSelfEmpls
interface "GET /self-employers/{vatin}" as getSelfEmplsId
interface "GET /orders/{id}" as getOrdersId
interface "GET /self-employers/{vatin}/orders" as getSelfEmplsIdOrders
interface "GET /self-employers/{vatin}/permissions" as getSelfEmplsIdPermission

Local --() getSelfEmpls
Local --() getOrdersId
Local --() getSelfEmplsIdOrders


component "External self-employer data" as External <<component>>
External --() getSelfEmplsId
External --() getSelfEmplsIdPermission

External -up-( getTaxpayerStatus
External -up-( getGrantedPermission

Component "Update self-employer" as Update <<component>>
interface "PUT /self-employers/{vatin}" as putSelfEmplsId
Update --() putSelfEmplsId
Update -up-( putTaxpayerData


Component "Delete self-employer" as Delete <<component>>
interface "DELETE /self-employers/{vatin}" as delSelfEmplsId

Delete --() delSelfEmplsId
Delete -up-( postPartnerUnbind
Delete -up-( postTaxpayerUnregistration

}

@enduml



@startuml incomes-components

component "АИС Налог-3\nПП НПД" as Tax3 <<component>>
interface "PostIncomeRequestV2" as PostIncome
interface "PostCancelReceiptRequestV2" as PostCancelReceipt
interface "GetIncomeRequestV2" as GetIncome
interface "GetIncomeForPeriodRequest" as GetIncomeForPeriod

Tax3 --() PostIncome
Tax3 --() PostCancelReceipt
Tax3 --() GetIncome
Tax3 --() GetIncomeForPeriod

component "Self-employed service" as SelfEmplService <<Component>>
interface "GET /self-employers/{id}/incomes" as getIncomes
interface "POST /self-employers/{id}/incomes" as postIncome
interface "GET /self-employers/{id}/incomes/{income-id}" as getIncomesId
interface "DELETE /self-employers/{id}/incomes/{income-id}" as delIncomesId
interface "GET /self-employers/{id}/incomes/statistics" as getIncomesStatistics

SelfEmplService --() getIncomes
SelfEmplService --() postIncome
SelfEmplService --() getIncomesId
SelfEmplService --() delIncomesId
SelfEmplService --() getIncomesStatistics

SelfEmplService -up-( PostIncome
SelfEmplService -up-( PostCancelReceipt
SelfEmplService -up-( GetIncome
SelfEmplService -up-( GetIncomeForPeriod

@enduml



@startuml account-components

component "АИС Налог-3\nПП НПД" as Tax3 <<component>>
interface "GetTaxpayerAccountStatusRequest" as GetAccountStatus
interface "GetAccrualsAndDebtsRequest" as GetAccrualsAndDebts
interface "GetPaymentDocumentsRequest" as GetPaymentDocuments

Tax3 --() GetAccountStatus
Tax3 --() GetAccrualsAndDebts
Tax3 --() GetPaymentDocuments

component "Self-employed service" as SelfEmplService <<Component>>
interface "GET /self-employers/{id}/account" as getAccount
interface "GET /self-employers/{id}/accruals" as getAccrualsAndDebts
interface "GET /self-employers/{id}/payment-documents" as getPaymentDocuments

SelfEmplService --() getAccount
SelfEmplService --() getAccrualsAndDebts
SelfEmplService --() getPaymentDocuments

SelfEmplService -up-( GetAccountStatus
SelfEmplService -up-( GetAccrualsAndDebts
SelfEmplService -up-( GetPaymentDocuments

@enduml



@startuml references-components

component "АИС Налог-3\nПП НПД" as Tax3 <<component>>
interface "GetRegistrationReferenceRequestV2" as GetRegistrationReference
interface "GetIncomeReferenceRequestV2" as GetIncomeReference

Tax3 --() GetRegistrationReference
Tax3 --() GetIncomeReference

component "Self-employed service" as SelfEmplService <<Component>>
interface "GET /self-employers/{id}/references/{type}" as getReference

SelfEmplService --() getReference

SelfEmplService -up-( GetRegistrationReference
SelfEmplService -up-( GetIncomeReference

@enduml



@startuml notifications-components

component "АИС Налог-3\nПП НПД" as Tax3 <<component>>
interface "GetNotificationsRequest" as GetNotifications
interface "PostNotificationsAckRequest" as PostNotificationsAck
interface "PostNotificationsArchRequest" as PostNotificationsArch
interface "PostNotificationsAckAllRequest" as PostNotificationsAckAll
interface "PostNotificationsArchAllRequest" as PostNotificationsArchAllRequest
interface "GetNotificationsCountRequest" as GetNotificationsCount
interface "PostNotificationsDeliveredRequest" as PostNotificationsDeliveredRequest

Tax3 --() GetNotifications
Tax3 --() PostNotificationsAck
Tax3 --() PostNotificationsArch
Tax3 --() PostNotificationsAckAll
Tax3 --() PostNotificationsArchAllRequest
Tax3 --() GetNotificationsCount
Tax3 --() PostNotificationsDeliveredRequest

component "Self-employed service" as SelfEmplService <<Component>>
interface "GET  /self-employers/{id}/notifications" as getNotifications
interface "GET  /self-employers/{id}/notifications/count" as getNotificationsCount
interface "POST /self-employers/{id}/notifications" as postNotifications
interface "PUT  /self-employers/{id}/notifications/{notif-id}" as putNotificationId

SelfEmplService --() getNotifications
SelfEmplService --() getNotificationsCount
SelfEmplService --() postNotifications
SelfEmplService --() putNotificationId

SelfEmplService -up-( GetNotifications
SelfEmplService -up-( PostNotificationsAck
SelfEmplService -up-( PostNotificationsArch
SelfEmplService -up-( PostNotificationsAckAll
SelfEmplService -up-( PostNotificationsArchAllRequest
SelfEmplService -up-( GetNotificationsCount
SelfEmplService -up-( PostNotificationsDeliveredRequest

@enduml



@startuml reference-data-components

component "АИС Налог-3\nПП НПД" as Tax3 <<component>>

interface "GetRegionsListRequest" as GetRegionsList
interface "GetActivitiesListRequestV2" as GetActivitiesList
interface "GetRejectionReasonsListRequest" as GetRejectionReasonsList
interface "GetTaxpayerUnregistrationReasonsListRequest" as GetTaxpayerUnregistrationReasonsList
interface "GetCancelIncomeReasonsListRequest" as GetCancelIncomeReasonsList

Tax3 --() GetRegionsList
Tax3 --() GetActivitiesList
Tax3 --() GetRejectionReasonsList
Tax3 --() GetCancelIncomeReasonsList
Tax3 --() GetTaxpayerUnregistrationReasonsList

component "Self-employed service" as SelfEmplService <<Component>>
interface "GET /reference-data/{type}" as getDictionary

SelfEmplService --() getDictionary

SelfEmplService -up-( GetRegionsList
SelfEmplService -up-( GetActivitiesList
SelfEmplService -up-( GetRejectionReasonsList
SelfEmplService -up-( GetCancelIncomeReasonsList
SelfEmplService -up-( GetTaxpayerUnregistrationReasonsList

@enduml