@startuml high-level-model-components

component "АИС Налог-3\nПП НПД" as Tax3 <<component>>
component "АИС Налог-3\nAuth service" as Tax3AuthService <<component>>
component "OpenAPI Gateway" as OpenAPI <<component>>

component "Self-employed service" as SelfEmplService <<component>>
component "Auth service" as AuthService <<component>>
component "Kafka Message bus" as  Kafka <<component>>
component "Object storage" as objectStorage <<Component>>

OpenAPI ..> Tax3: use internal API
OpenAPI ..> Tax3AuthService: use authorize partner API

SelfEmplService ..> OpenAPI: use public API
SelfEmplService ..> AuthService: change User role
SelfEmplService ..> Kafka: consume & public events
SelfEmplService ..> objectStorage: save media files

@enduml



@startuml gateway-messaging-components

component "OpenAPI Gateway" as OpenAPI <<component>>
interface "SendMessageRequest" as sendMessage
interface "GetMessageRequest" as getMessage
interface "GetMessagesRequest" as sendMessages

component "Self-employed service" as SelfEmplService <<component>>

OpenAPI --() sendMessage
OpenAPI --() getMessage
OpenAPI --() sendMessages

SelfEmplService -up-( sendMessage
SelfEmplService -up-( getMessage
SelfEmplService -up-( sendMessages

@enduml



@startuml authentication-components

component "АИС Налог-3\nAuth service" as Tax3AuthService <<component>>
interface "AuthRequest" as authRequest
component "Self-employed service" as SelfEmplService <<service>>

Tax3AuthService --() authRequest
SelfEmplService -up-( authRequest

@enduml



@startuml platform-registration-components

component "АИС Налог-3\nПП НПД" as Tax3 <<component>>
interface "PostPlatformRegistrationRequest" as postPlatformRegistration
component "Self-employed service" as SelfEmplService <<service>>

Tax3 --() postPlatformRegistration
SelfEmplService -up-( postPlatformRegistration

@enduml



@startuml self-employer-components

component "АИС Налог-3\nПП НПД" as Tax3 <<component>>
interface "GetTaxpayerRestrictionsRequest" as getTaxpayerRestrictions
interface "PostRegistrationRequest\nGetRegistrationStatusRequest" as postTaxpayerRegistration
interface "GetTaxpayerStatusRequest" as getTaxpayerStatus
interface "PutTaxpayerDataRequest" as putTaxpayerData
interface "GetGrantedPermissionsRequest" as getGrantedPermission
interface "GetInnByPersonalInfoRequestV3" as getInnByPersonalInfo
interface "PostBindPartnerWithInnRequest\nGetBindPartnerStatusRequest" as postPartnerBindInn
interface "PostBindPartnerWithPhoneRequest\nGetBindPartnerStatusRequest" as postPartnerBindPhone
interface "PostUnbindPartnerRequest" as postPartnerUnbind
interface "PostUnregistrationRequestV2\nGetUnregistrationStatusRequest" as postTaxpayerUnregistration

Tax3 --() getTaxpayerRestrictions
Tax3 --() postTaxpayerRegistration
Tax3 --() getTaxpayerStatus
Tax3 --() putTaxpayerData
Tax3 --() postPartnerBindInn
Tax3 --() postPartnerBindPhone
Tax3 --() postTaxpayerUnregistration
Tax3 --() postPartnerUnbind
Tax3 --() getGrantedPermission
Tax3 --() getInnByPersonalInfo

component "Self-employed service" as SelfEmplService <<service>> {

component "Registration info" as RegInfo <<component>>
interface "GET /restrictions/{vatin}" as getRestrictions
interface "POST /vatin-request/" as postVatinRequest

RegInfo -up-( getTaxpayerRestrictions
RegInfo -up-( getInnByPersonalInfo

RegInfo --() getRestrictions
RegInfo --() postVatinRequest

component "Create self-employer" as CreateSelfEmpl <<component>>
interface "POST /self-employers/" as postSelfEmpls

CreateSelfEmpl --() postSelfEmpls

CreateSelfEmpl -up-( postTaxpayerRegistration
CreateSelfEmpl -up-( postPartnerBindInn
CreateSelfEmpl -up-( postPartnerBindPhone

component "Local self-employers data" as Local <<component>>
interface "GET /self-employers/" as getSelfEmpls
interface "GET /self-employers/{vatin}" as getSelfEmplsId
interface "GET /orders/{id}" as getOrdersId
interface "GET /self-employers/{vatin}/orders" as getSelfEmplsIdOrders
interface "GET /self-employers/{vatin}/permissions" as getSelfEmplsIdPermission

Local --() getSelfEmpls
Local --() getOrdersId
Local --() getSelfEmplsIdOrders


component "External self-employer data" as External <<component>>
External --() getSelfEmplsId
External --() getSelfEmplsIdPermission

External -up-( getTaxpayerStatus
External -up-( getGrantedPermission

Component "Update self-employer" as Update <<component>>
interface "PUT /self-employers/{vatin}" as putSelfEmplsId
Update --() putSelfEmplsId
Update -up-( putTaxpayerData


Component "Delete self-employer" as Delete <<component>>
interface "DELETE /self-employers/{vatin}" as delSelfEmplsId

Delete --() delSelfEmplsId
Delete -up-( postPartnerUnbind
Delete -up-( postTaxpayerUnregistration

}

@enduml



@startuml incomes-components

component "АИС Налог-3\nПП НПД" as Tax3 <<component>>
interface "PostIncomeRequestV2" as postIncomeRequestV2
interface "PostCancelReceiptRequestV2" as postCancelReceipt
interface "GetIncomeRequestV2" as getIncomeRequestV2
interface "GetIncomeForPeriodRequest" as getIncomeForPeriod

Tax3 --() postIncomeRequestV2
Tax3 --() postCancelReceipt
Tax3 --() getIncomeRequestV2
Tax3 --() getIncomeForPeriod
Tax3 --() getKeys

component "Self-employed service" as SelfEmplService <<Component>>
interface "GET /self-employers/{id}/incomes" as getIncomes
interface "POST /self-employers/{id}/incomes" as postIncome
interface "GET /self-employers/{id}/incomes/{income-id}" as getIncomesId
interface "DELETE /self-employers/{id}/incomes/{income-id}" as delIncomesId
interface "GET /self-employers/{id}/incomes/statistics" as getIncomesStatistics

SelfEmplService --() getIncomes
SelfEmplService --() postIncome
SelfEmplService --() getIncomesId
SelfEmplService --() delIncomesId
SelfEmplService --() getIncomesStatistics

SelfEmplService -up-( postIncomeRequestV2
SelfEmplService -up-( postCancelReceipt
SelfEmplService -up-( getIncomeRequestV2
SelfEmplService -up-( getIncomeForPeriod
SelfEmplService -up-( getKeys

@enduml

@startuml offline-incomes-components

component "АИС Налог-3\nПП НПД" as Tax3 <<component>>
interface "GetKeysRequest" as getKeys
interface "PostIncomeRequestV2" as postIncomeRequestV2

Tax3 --() getKeys
Tax3 --() postIncomeRequestV2

component "Self-employed service" as SelfEmplService <<Component>>
component "Object storage" as objectStorage <<Component>>

SelfEmplService -up-( getKeys
SelfEmplService -up-( postIncomeRequestV2
SelfEmplService ..> objectStorage: save receipt image file

@enduml



@startuml account-components

component "АИС Налог-3\nПП НПД" as Tax3 <<component>>
interface "GetTaxpayerAccountStatusRequest" as getAccountStatus
interface "GetAccrualsAndDebtsRequest" as getAccrualsAndDebtsRequest
interface "GetPaymentDocumentsRequest" as GetPaymentDocumentsRequest

Tax3 --() getAccountStatus
Tax3 --() getAccrualsAndDebtsRequest
Tax3 --() GetPaymentDocumentsRequest

component "Self-employed service" as SelfEmplService <<Component>>
interface "GET /self-employers/{id}/account" as getAccount
interface "GET /self-employers/{id}/accruals" as getAccrualsAndDebts
interface "GET /self-employers/{id}/payment-documents" as getPaymentDocuments

SelfEmplService --() getAccount
SelfEmplService --() getAccrualsAndDebts
SelfEmplService --() getPaymentDocuments

SelfEmplService -up-( getAccountStatus
SelfEmplService -up-( getAccrualsAndDebtsRequest
SelfEmplService -up-( GetPaymentDocumentsRequest

@enduml



@startuml references-components

component "АИС Налог-3\nПП НПД" as Tax3 <<component>>
interface "GetRegistrationReferenceRequestV2" as GetRegistrationReference
interface "GetIncomeReferenceRequestV2" as GetIncomeReference

Tax3 --() GetRegistrationReference
Tax3 --() GetIncomeReference

component "Self-employed service" as SelfEmplService <<Component>>
interface "GET /self-employers/{id}/references/{type}" as getReference

SelfEmplService --() getReference

SelfEmplService -up-( GetRegistrationReference
SelfEmplService -up-( GetIncomeReference

@enduml



@startuml notifications-components

component "АИС Налог-3\nПП НПД" as Tax3 <<component>>
interface "GetNotificationsRequest" as getNotificationsRequest
interface "PostNotificationsAckRequest" as postNotificationsAck
interface "PostNotificationsArchRequest" as postNotificationsArch
interface "PostNotificationsAckAllRequest" as postNotificationsAckAll
interface "PostNotificationsArchAllRequest" as postNotificationsArchAllRequest
interface "GetNotificationsCountRequest" as getNotificationsCountRequest
interface "PostNotificationsDeliveredRequest" as postNotificationsDeliveredRequest

Tax3 --() getNotificationsRequest
Tax3 --() postNotificationsAck
Tax3 --() postNotificationsArch
Tax3 --() postNotificationsAckAll
Tax3 --() postNotificationsArchAllRequest
Tax3 --() getNotificationsCountRequest
Tax3 --() postNotificationsDeliveredRequest

component "Self-employed service" as SelfEmplService <<Component>>
interface "GET  /self-employers/{id}/notifications" as getNotifications
interface "GET  /self-employers/{id}/notifications/count" as getNotificationsCount
interface "POST /self-employers/{id}/notifications" as postNotifications
interface "PUT  /self-employers/{id}/notifications/{notif-id}" as putNotificationId

SelfEmplService --() getNotifications
SelfEmplService --() getNotificationsCount
SelfEmplService --() postNotifications
SelfEmplService --() putNotificationId

SelfEmplService -up-( getNotificationsRequest
SelfEmplService -up-( postNotificationsAck
SelfEmplService -up-( postNotificationsArch
SelfEmplService -up-( postNotificationsAckAll
SelfEmplService -up-( postNotificationsArchAllRequest
SelfEmplService -up-( getNotificationsCountRequest
SelfEmplService -up-( postNotificationsDeliveredRequest

@enduml



@startuml reference-data-components

component "АИС Налог-3\nПП НПД" as Tax3 <<component>>

interface "GetRegionsListRequest" as getRegionsList
interface "GetActivitiesListRequestV2" as getActivitiesList
interface "GetRejectionReasonsListRequest" as getRejectionReasonsList
interface "GetTaxpayerUnregistrationReasonsListRequest" as getTaxpayerUnregistrationReasonsList
interface "GetCancelIncomeReasonsListRequest" as getCancelIncomeReasonsList

Tax3 --() getRegionsList
Tax3 --() getActivitiesList
Tax3 --() getRejectionReasonsList
Tax3 --() getTaxpayerUnregistrationReasonsList
Tax3 --() getCancelIncomeReasonsList

component "Self-employed service" as SelfEmplService <<Component>>
interface "GET /reference-data/{type}" as getDictionary

SelfEmplService --() getDictionary

SelfEmplService -up-( getRegionsList
SelfEmplService -up-( getActivitiesList
SelfEmplService -up-( getRejectionReasonsList
SelfEmplService -up-( getTaxpayerUnregistrationReasonsList
SelfEmplService -up-( getCancelIncomeReasonsList

@enduml