@startuml initialization-in-tax-3

@enduml

@startuml self-employer-components

component "АИС Налог-3\nПП НПД" as Tax3 <<component>>
interface "GetTaxpayerRestrictionsRequest" as taxpayerRestrictions
interface "PostRegistrationRequest\nGetRegistrationStatusRequest" as taxpayerRegistration
interface "GetTaxpayerStatusRequest" as taxpayerStatus
interface "PutTaxpayerDataRequest" as taxpayerData
interface "GetGrantedPermissionsRequest" as getGrantedPermission
interface "GetInnByPersonalInfoRequestV3" as getInnByPersonalInfo
interface "PostBindPartnerWithInnRequest\nGetBindPartnerStatusRequest" as partnerBindInn
interface "PostBindPartnerWithPhoneRequest\nGetBindPartnerStatusRequest" as partnerBindPhone
interface "PostUnbindPartnerRequest" as partnerUnbind
interface "PostUnregistrationRequestV2\nGetUnregistrationStatusRequest" as taxpayerUnregistration
interface "GetTaxpayerUnregistrationReasonsListRequest" as getTaxpayerUnregistrationReasonsList

Tax3 --() taxpayerRestrictions
Tax3 --() taxpayerRegistration
Tax3 --() taxpayerStatus
Tax3 --() taxpayerData
Tax3 --() partnerBindInn
Tax3 --() partnerBindPhone
Tax3 --() taxpayerUnregistration
Tax3 --() partnerUnbind
Tax3 --() getGrantedPermission
Tax3 --() getInnByPersonalInfo
Tax3 --() getTaxpayerUnregistrationReasonsList

component "Self-employed service" as SelfEmplService <<service>> {

component "Registration" as Registration <<component>>
interface "GET /restrictions/{vatin}" as getRestrictions
interface "POST /self-employers/" as postSelfEmpls
interface "DELETE /self-employers/{id}" as delSelfEmplsId

component "Information" as Information <<component>>
interface "GET /self-employers/" as getSelfEmpls
interface "GET /self-employers/{id}" as getSelfEmplsId

Component "Change" as Update <<component>>
interface "PATCH /self-employers/{id}" as patchSelfEmplsId
interface "GET /orders/{id}" as getOrdersId

}

SelfEmplService --() getRestrictions
SelfEmplService --() getSelfEmpls
SelfEmplService --() postSelfEmpls
SelfEmplService --() getSelfEmplsId
SelfEmplService --() patchSelfEmplsId
SelfEmplService --() delSelfEmplsId
SelfEmplService --() getOrdersId

SelfEmplService -up-( taxpayerRestrictions
SelfEmplService -up-( taxpayerRegistration
SelfEmplService -up-( taxpayerStatus
SelfEmplService -up-( taxpayerData
SelfEmplService -up-( partnerBind
SelfEmplService -up-( taxpayerUnregistration

@enduml



@startuml incomes-components

component "АИС Налог-3\nПП НПД" as Tax3 <<Component>>
interface "PostIncomeRequestV2" as PostIncome
interface "PostCancelReceiptRequestV2" as PostCancelReceipt
interface "GetIncomeRequestV2" as GetIncome
interface "GetIncomeForPeriodRequest" as GetIncomeForPeriod

Tax3 --() PostIncome
Tax3 --() PostCancelReceipt
Tax3 --() GetIncome
Tax3 --() GetIncomeForPeriod

component "Self-employed service" as SelfEmplService <<Component>>
interface "GET /self-employers/{id}/incomes" as getIncomes
interface "POST /self-employers/{id}/incomes" as postIncome
interface "GET /self-employers/{id}/incomes/{income-id}" as getIncomesId
interface "DELETE /self-employers/{id}/incomes/{income-id}" as delIncomesId
interface "GET /self-employers/{id}/incomes/statistics" as getIncomesStatistics

SelfEmplService --() getIncomes
SelfEmplService --() postIncome
SelfEmplService --() getIncomesId
SelfEmplService --() delIncomesId
SelfEmplService --() getIncomesStatistics

SelfEmplService -up-( PostIncome
SelfEmplService -up-( PostCancelReceipt
SelfEmplService -up-( GetIncome
SelfEmplService -up-( GetIncomeForPeriod

@enduml



@startuml account-components

component "АИС Налог-3\nПП НПД" as Tax3 <<Component>>
interface "GetTaxpayerAccountStatusRequest" as GetAccountStatus
interface "GetAccrualsAndDebtsRequest" as GetAccrualsAndDebts
interface "GetPaymentDocumentsRequest" as GetPaymentDocuments

Tax3 --() GetAccountStatus
Tax3 --() GetAccrualsAndDebts
Tax3 --() GetPaymentDocuments

component "Self-employed service" as SelfEmplService <<Component>>
interface "GET /self-employers/{id}/account" as getAccount
interface "GET /self-employers/{id}/accruals" as getAccrualsAndDebts
interface "GET /self-employers/{id}/payment-documents" as getPaymentDocuments

SelfEmplService --() getAccount
SelfEmplService --() getAccrualsAndDebts
SelfEmplService --() getPaymentDocuments

SelfEmplService -up-( GetAccountStatus
SelfEmplService -up-( GetAccrualsAndDebts
SelfEmplService -up-( GetPaymentDocuments

@enduml



@startuml reference-components

component "АИС Налог-3\nПП НПД" as Tax3 <<Component>>
interface "GetRegistrationReferenceRequestV2" as GetRegistrationReference
interface "GetIncomeReferenceRequestV2" as GetIncomeReference

Tax3 --() GetRegistrationReference
Tax3 --() GetIncomeReference

component "Self-employed service" as SelfEmplService <<Component>>
interface "GET /self-employers/{id}/reference/{type}" as getReference

SelfEmplService --() getReference

SelfEmplService -up-( GetRegistrationReference
SelfEmplService -up-( GetIncomeReference

@enduml



@startuml notifications-components

component "АИС Налог-3\nПП НПД" as Tax3 <<Component>>
interface "GetNotificationsRequest" as GetNotifications
interface "PostNotificationsAckRequest" as PostNotificationsAck
interface "PostNotificationsArchRequest" as PostNotificationsArch
interface "PostNotificationsAckAllRequest" as PostNotificationsAckAll
interface "PostNotificationsArchAllRequest" as PostNotificationsArchAllRequest
interface "GetNotificationsCountRequest" as GetNotificationsCount
interface "PostNotificationsDeliveredRequest" as PostNotificationsDeliveredRequest

Tax3 --() GetNotifications
Tax3 --() PostNotificationsAck
Tax3 --() PostNotificationsArch
Tax3 --() PostNotificationsAckAll
Tax3 --() PostNotificationsArchAllRequest
Tax3 --() GetNotificationsCount
Tax3 --() PostNotificationsDeliveredRequest

component "Self-employed service" as SelfEmplService <<Component>>
interface "GET  /self-employers/{id}/notifications" as getNotifications
interface "GET  /self-employers/{id}/notifications/count" as getNotificationsCount
interface "POST /self-employers/{id}/notifications" as postNotifications
interface "PUT  /self-employers/{id}/notifications/{notif-id}" as putNotificationId

SelfEmplService --() getNotifications
SelfEmplService --() getNotificationsCount
SelfEmplService --() postNotifications
SelfEmplService --() putNotificationId

SelfEmplService -up-( GetNotifications
SelfEmplService -up-( PostNotificationsAck
SelfEmplService -up-( PostNotificationsArch
SelfEmplService -up-( PostNotificationsAckAll
SelfEmplService -up-( PostNotificationsArchAllRequest
SelfEmplService -up-( GetNotificationsCount
SelfEmplService -up-( PostNotificationsDeliveredRequest

@enduml



@startuml dictionaries-components

component "АИС Налог-3\nПП НПД" as Tax3 <<Component>>\

interface "GetRegionsListRequest" as GetRegionsList
interface "GetActivitiesListRequestV2" as GetActivitiesList
interface "GetRejectionReasonsListRequest" as GetRejectionReasonsList
interface "GetTaxpayerUnregistrationReasonsListRequest" as GetTaxpayerUnregistrationReasonsList
interface "GetCancelIncomeReasonsListRequest" as GetCancelIncomeReasonsList

Tax3 --() GetRegionsList
Tax3 --() GetActivitiesList
Tax3 --() GetRejectionReasonsList
Tax3 --() GetUnregistrationReasonsList
Tax3 --() GetCancelIncomeReasonsList

component "Self-employed service" as SelfEmplService <<Component>>
interface "GET /dictionaries/{type}" as getDictionary

SelfEmplService --() getDictionary

SelfEmplService -up-( GetRegionsList
SelfEmplService -up-( GetActivitiesList
SelfEmplService -up-( GetRejectionReasonsList
SelfEmplService -up-( GetUnregistrationReasonsList
SelfEmplService -up-( GetCancelIncomeReasonsList

@enduml