@startuml

[*] -> Pending

Pending -> Active: Order completed
Active -> Pending: Order registered

Pending -> Unactive: Order completed \n or failed
Unactive --> Pending: Order registered

Active -> Unactive: Default unbind

Pending: do / Show order status

Active: do / Unbind self-employer

Unactive: do / Bind self-employer

@enduml