@startuml

[*] --> Pending

Pending -> Active: Creation order COMPLITED
Active --> Pending

Pending -> Unactive
Unactive -> Pending

Active -> Unactive

Pending: entry / Create self-employer
Pending: entry / Unregistration self-employer

Pending: exit / Order get state COMPLETED
Pending: exit / Order get state FAILED

@enduml