@startuml identity-management-components

!includesub ../.components/auth-service.puml!COMPONENT
!includesub ../.components/auth-service.puml!CLIENT_API

component "Web site or Mobile app" as Client <<Client>>

Client -up-( authorize
Client -up-( token
Client -up-( userinfo
Client -up-( logout

@enduml