@startuml identity-management-components

!include ../.library/components/internet-bank/auth-service.puml!interfaces

component "Web site or Mobile app" as Client <<Client>>

Client -up-( getAuthorize
Client -up-( postToken
Client -up-( getUserinfo
Client -up-( getLogout

@enduml